<?php
    echo '<div class="availability_item">';
	if($url) {
		echo '<div class="delimiter"></div>';
		echo '<a href="'.$url.'" class="'.$level.'" title="'.$this->transEsc($label).'">'.$this->translate($label).'</a><br/>';
	} else {
		echo '<div class="delimiter"></div>';
		echo '<span class="'.$level.'" title="'.$this->transEsc($label).'">'.$this->translate($label).'</span><br/>';
	}
    echo '</div>';
?>
